<?php

  function pfooter(){
?>
    </div>

    <div class="e-footer">
      Site &copy; <?php echo date("Y"); ?> <a href="./"><?php if( EETI_INSTALLED ) echo EETI_CONFIG_TITLE; else echo "eeti.me"; ?></a>.<br>
      <div class="tip">Uploaded content is &copy; their respective owners. (<?php if( EETI_INSTALLED ) echo EETI_CONFIG_TITLE; else echo "eeti.me"; ?> is still in <a href="https://en.wikipedia.org/wiki/Software_release_life_cycle#Alpha">alpha</a>. Things might break or get reset. Sorry.)</div>
      <!-- generated by <?php echo getVersion(); ?> -->
    </div>
  </body>
</html>
<?php

  }

?>
